import os
from dotenv import load_dotenv
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_classic.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

# Import our custom modules
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
from src.database.vector_store import load_existing_vector_store
from src.ingestion.document_loader import load_pdf, chunk_documents
from src.retrieval.hybrid_retriever import build_hybrid_retriever

load_dotenv()

def build_advanced_retriever(base_retriever, top_k=3):
    """
    Wraps an existing retriever (like our Hybrid Retriever) with a Cross-Encoder.
    It takes the broad results (e.g., 10 chunks) and rescores them down to top_k.
    """
    print("Loading local Cross-Encoder model (ms-marco-MiniLM)...")
    # This specific model was trained by Microsoft specifically for Q&A ranking
    cross_encoder_model = HuggingFaceCrossEncoder(model_name="cross-encoder/ms-marco-MiniLM-L-6-v2")
    
    print(f"Setting up reranker to compress results down to top {top_k}...")
    compressor = CrossEncoderReranker(model=cross_encoder_model, top_n=top_k)
    
    # ContextualCompressionRetriever passes the base results into our compressor
    compression_retriever = ContextualCompressionRetriever(
        base_compressor=compressor,
        base_retriever=base_retriever
    )
    
    return compression_retriever

# --- Local Testing Block ---
if __name__ == "__main__":
    SAMPLE_PDF_PATH = os.path.join(os.path.dirname(__file__), "../../data/raw/sample_climate_report.pdf")
    
    try:
        # 1. Setup the base data and database
        print("Preparing baseline data...")
        pages = load_pdf(SAMPLE_PDF_PATH)
        doc_chunks = chunk_documents(pages)
        db = load_existing_vector_store()
        
        # 2. Build the Hybrid Retriever (returns ~10 chunks)
        hybrid_retriever = build_hybrid_retriever(doc_chunks, db)
        
        # 3. Wrap it in our Advanced Cross-Encoder Retriever (compresses to 3 chunks)
        advanced_retriever = build_advanced_retriever(hybrid_retriever, top_k=3)
        
        test_query = "What is the exact target for global surface temperature?"
        print(f"\n--- Testing Advanced Reranked Search ---")
        print(f"Query: '{test_query}'\n")
        
        # Invoke the advanced retriever
        print("Searching and Reranking (this requires heavy math, please wait)...")
        results = advanced_retriever.invoke(test_query)
        
        print(f"\nSuccessfully compressed to {len(results)} highly relevant chunks:")
        for i, res in enumerate(results):
            print(f"\nFinal Rank {i+1} (Page {res.metadata.get('page', 'Unknown')}):")
            # We print the relevance score generated by the cross-encoder
            print(f"Relevance Score: {res.metadata.get('relevance_score', 'N/A')}")
            print(f"{res.page_content[:200]}...")
            
    except Exception as e:
        print(f"Failed during advanced retrieval: {e}")